---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/terraform
    tag: 1

inputs:
  - name: repo

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      TF_WORKSPACE=`cat ./.git/resource/head_name`
      apk add --update --no-progress bash jq
      bash ./ci/tasks/apply_terraform.sh