---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/spp-terraform
    tag: 1

inputs:
  - name: spp-sml-portal
  - name: build

run:
  path: sh
  args:
    - -exc
    - |
      apk add --update --no-progress bash jq
      bash ./ci/tasks/apply_terraform.sh