---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/terraform
    tag: 1

inputs:
  - name: repo
  - name: branch-info

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      WORKSPACE=$(<branch-info)
      apk add --update --no-progress bash jq
      bash ./ci/tasks/apply_terraform.sh