---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/python-poetry
    tag: 3.9

inputs:
  - name: repo
outputs:
  - name: build.zip

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      apk add --update --no-progress bash jq
      bash ./ci/tasks/build_files.sh
