---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/python-selenium
    tag: 4

inputs:
  - name: repo

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      apk add --update --no-progress bash jq
      bash ./ci/tasks/deploy.sh
