---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/python-poetry
    tag: 3.9

inputs:
  - name: repo
outputs:
  - name: repo
run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      cat .git/resource/head_name > ./current-branch
      cat ./current-branch
      cat .git/resource/metadata.json