# This is the pipeline to run the BDD tests on prod, pre-prod and dev.
# The triggers are daily for now, a ticket has been written to address push to branch triggers.
env_setups:
  general: &general_params
    AWS_DEFAULT_REGION: eu-west-2
    S3_ACCOUNT_STATE_KEY: ons-smlportal-dev.account.tfstate
    S3_ENVIRONMENT_STATE_KEY: ons-smlportal-dev.environment.tfstate
    CONCOURSE_ACCESS_TOKEN: ((github_access_token))
    SHARED_ACCOUNT_ROLE: &shared_account_role arn:aws:iam::289259348294:role/spp-concourse-access-prod

  general_dev: &general_dev_params
    TF_VAR_deployment_type:
    <<: *general_params

  # -------------------

  sml_dev: &sml_dev_setup
    <<: *general_dev_params
    ACCOUNT_NAME: &account sml_dev
    AWS_ACCOUNT_ID: ((aws_account_sml_dev))
    AWS_SERVICE_ROLE>: &role arn:aws:iam::((aws_account_sml_dev)):role/spp-concourse-sml-deployment-dev
    TF_VAR_deployment_role: *role
    TF_VAR_environment: dev
    TF_VAR_account: *account


resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
 # - name: main
 #   type: git
 #   icon: github
 #   check_every: never
 #   webhook_token: gesture
 #   source:
 #     uri: https://github.com/ONSdigital/sml-catalogue.git
 #     branch: main
 #     username: ((github_access_token))
 #     password: x-oauth-basic
 # - name: bdd-test-timer
 #   type: time
 #   source:
 #     # Triggers the tests once per day, just after 7:30am.
 #     start: 7:30
 #     stop: 7:45
 #     location: Europe/London
 #     days: [Monday, Tuesday, Wednesday, Thursday, Friday]
  - name: pr-open
    type: pull-request
    icon: github
    check_every: never
    webhook_token: gesture
    source:
      repository: ONSdigital/sml-catalogue
      access_token: ((new_github_access_token))
      base_branch: main
      disable_forks: true
      states: ["OPEN"]
  #- name: pr-done
  #  type: pull-request
  #  icon: github
  #  check_every: never
  #  webhook_token: gesture
  #  source:
  #    repository: ONSdigital/sml-catalogue
  #    access_token: ((github_access_token))
  #    base_branch: main
  #    disable_forks: true
  #    states: ["CLOSED", "MERGED"]
  #
jobs:
  - name: dev-bdd-tests
    plan:
      - do:
        - get: repo
          resource: pr-open
          trigger: true
          version: every
        - put: repo
          resource: pr-open
          params:
            path: repo
            status: pending
            context: behave-tests
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://d1jgbw8ee9pybj.cloudfront.net/'}
          inputs:
            - name: repo
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p ./features/test_reports/dev/$date
              pipenv run behave -D host=$ENDPOINT --junit --junit-directory ./features/test_reports/dev/$date
              cd ./features/test_reports/dev/$date
              ls
              cat TESTS-about.xml TESTS-accessibility.xml TESTS-cookies.xml TESTS-footer.xml TESTS-glossary.xml TESTS-header.xml TESTS-help_center.xml TESTS-method_summary.xml TESTS-methods.xml > test_report.xml
              cat test_report.xml
    on_success:
      put: repo
      resource: pr-open
      params:
        path: repo
        status: success
        context: dev-bdd-tests
    on_failure:
      put: repo
      resource: pr-open
      params:
        path: repo
        status: success
        context: dev-bdd-tests