name: Deploy preprod and prod

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preprod:
    uses: ./.github/workflows/reusable.yml
    with:
      workspace: main
      environment: preprod

      state_bucket: statistical-methods-library-tf-state-preprod
    secrets: 
      DEPLOYMENT_ROLE: ${{ secrets.PREPROD_DEPLOYMENT_ROLE }}
  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/reusable.yml
    with:
      workspace: main
      environment: prod
      state_bucket: statistical-methods-library-tf-state-prod
    secrets: 
      DEPLOYMENT_ROLE: ${{ secrets.PROD_DEPLOYMENT_ROLE }}