name: Deploy workspace

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/reusable.yml
    with:
      workspace: ${{github.head_ref}}
      environment: Development
      state_bucket: statistical-methods-library-tf-state
    secrets: 
      DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}