name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/reusable.yml
    with:
      my_var: "Just a string"
    secrets: inherit