name: Linting
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: cd ${{ github.workspace }}/sml_builder && pylint .
      - run: echo "🍏 This job's status is ${{ job.status }}."
