name: Linting
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: pip install black
      - run: black --check --diff ${{ github.workspace }}/sml_builder
      - run: echo "This job's status is ${{ job.status }}."
