name: Reusable workflow example

on:
  workflow_call:
    inputs:
      my_var:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{my_var}}